### PR TITLE
Update Android Gradle plugin 7.3.1

### PR DESCRIPTION
**Pull request by BartoszLitwiniuk**

### CODE REVIEW

**Comment by vlussenburg** [comment]
I think this is fixed by going to the latest commit like we did in the crashloop detection branch

**Comment by BartoszLitwiniuk** [comment]
> I think this is fixed by going to the latest commit like we did in the crashloop detection branch

There isn't any commit which changing sdk/gradle plugin version @vlussenburg

**Comment by vlussenburg** [comment]
I meant latest version of crashpad. I recognize the compilation error from when we tried to build Crashpad with the latest ndk. Let me fetch commit id

**Comment by vlussenburg** [comment]
https://github.com/backtrace-labs/crashpad/commit/7c6dc0a3863e355f55cd1b597b368a7bb1445a84

**Comment by vlussenburg** [comment]
And this commit on this repo:
https://github.com/backtrace-labs/backtrace-android/pull/80/commits/5528917b16eaf8ff7f7ae912578628a3fd74c62a

**Comment by BartoszLitwiniuk** [comment]
I've decided to split this PR into two:
- this PR will only update android gradle plugin - so we will be able to merge
- PR with updating SDK what is currently blocked by problems with crashpad https://github.com/backtrace-labs/backtrace-android/pull/87

**Comment by vlussenburg** [comment]
@BartoszLitwiniuk the problem is already resolved, pls update the crashpad submodule git commit as I indicated in my comments :)

**Review by vlussenburg — APPROVED** [review]

**Comment by vlussenburg** [comment]
@BartoszLitwiniuk there, fixed :)

**Pull request merged**
