### PR TITLE
Upgrade action versions for actions that use node12 that is about to be deprecated on GitHub Actions

### PR DESCRIPTION
**Pull request by vlussenburg**

### CODE REVIEW

**Comment by vlussenburg** [comment]
Action fails, but v2 was released:
https://github.com/saucelabs/saucectl-run-action/compare/v2.0.0...main

Try to run again later.

**Comment by BartoszLitwiniuk** [comment]
test failed

**Comment by konraddysput** [comment]
Does this pull request update the node version? If it does, does it make sense to use node16 to prevent updating this repo in next year?

**Comment by vlussenburg** [comment]
@konraddysput yep, that's the reason this PR exists :). Having some issues with the saucectl action still

**Comment by vlussenburg** [comment]
@BartoszLitwiniuk it's green, can you review pls?

**Review by BartoszLitwiniuk — APPROVED** [review]
lgtm

**Pull request merged**
